Header in progress
orlovaad/WebHero pull request #3
Opened 2022-02-17 09:28 UTC by orlovaad

2022-02-17 11:22 UTC, agatta17 requested changes

2022-02-17 11:22 UTC, agatta17 commented on style.css
> +  }
Можно использовать max-width, min-width, max-height и min-height для более универсальной верстки. Это позволит не писать часть медиазапросов. Здесь это применимо.

2022-02-17 11:22 UTC, agatta17 commented on style.css
> +  }
ширина и фон не поменялись, их не нужно переопределять для мобилки

2022-02-17 11:22 UTC, agatta17 commented on style.css
> +    font: 800 25px/31px Gilroy;
поменялся только размер шрифта, не нужно переопределять весь font

2022-02-17 11:22 UTC, agatta17 commented on style.css
> +    color: #fff;
цвет не изменился

2022-02-17 11:22 UTC, agatta17 commented on style.css
> +    font: 800 20px/25px Gilroy;
поменялся только размер шрифта, не нужно переопределять весь font

2022-02-17 11:22 UTC, agatta17 commented on style.css
> +    width: 80%;
ширина не изменилась

2022-02-17 11:22 UTC, agatta17 commented on style.css
> +    font: 300 15px/17px Gilroy;
поменялся только размер шрифта, не нужно переопределять весь font

2022-02-17 11:22 UTC, agatta17 commented on style.css
>    flex-grow: 2;
почему 2, а не 1?

2022-02-18 13:58 UTC, agatta17 requested changes

2022-02-18 13:58 UTC, agatta17 commented on style.css
> +.logo-container {
кажется, в разметке нет такого класса

2022-02-18 13:58 UTC, agatta17 commented on style.css
> +  justify-content: flex-start;
если заменить на justify-content: space-between, содержимое не будет съезжать влево, и все будет совсем ровно

2022-02-18 13:58 UTC, agatta17 commented on style.css
> +  align-self: center;
свойство работает только для элементов, расположенных внутри флекс-контейнера

2022-02-18 13:58 UTC, agatta17 commented on style.css
> +  width: 380px;
на телефонах шириной 320 не влезает

2022-02-18 13:58 UTC, agatta17 commented on style.css
> +@media (min-width: 14400px) {
что это?)

2022-02-18 14:10 UTC, orlovaad commented on style.css
> +@media (min-width: 14400px) {
это остатки прежней роскоши

2022-02-19 06:45 UTC, merged